// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import edu.wpi.first.wpilibj2.command.WaitCommand;
import frc.robot.subsystems.LiftSubsystem;
import frc.robot.subsystems.DriveSubsystem;
import frc.robot.subsystems.ControlPanelSubsystem;
import frc.robot.subsystems.FuelShooterPIDSubsystem;
import frc.robot.subsystems.FuelDeliverySubSystem;

import edu.wpi.first.wpilibj.controller.PIDController;
import edu.wpi.first.wpilibj.controller.RamseteController;
import frc.robot.Constants.DriveConstants;
import frc.robot.Constants.AutoConstants;
import edu.wpi.first.wpilibj.controller.SimpleMotorFeedforward;
import edu.wpi.first.wpilibj.geometry.Pose2d;
import edu.wpi.first.wpilibj.geometry.Rotation2d;
import edu.wpi.first.wpilibj.geometry.Translation2d;
import edu.wpi.first.wpilibj.trajectory.Trajectory;
import edu.wpi.first.wpilibj.trajectory.TrajectoryConfig;
import edu.wpi.first.wpilibj.trajectory.TrajectoryGenerator;
import edu.wpi.first.wpilibj.trajectory.constraint.DifferentialDriveVoltageConstraint;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.RamseteCommand;
import edu.wpi.first.wpilibj2.command.RunCommand;
import edu.wpi.first.wpilibj2.command.button.JoystickButton;
import java.util.List;


/**
 *
 */
public class AutoDemoTest extends SequentialCommandGroup {
    
    private final LiftSubsystem m_liftSubsystem;
    private final DriveSubsystem m_driveSubsystem;
    private final ControlPanelSubsystem m_controlPanelSubsystem;
    private final FuelShooterPIDSubsystem m_fuelShooterPIDSubsystem;
    private final FuelDeliverySubSystem m_fuelDeliverySubSystem;

    public AutoDemoTest(LiftSubsystem subsystemLift, 
                        DriveSubsystem subsystemDrive, 
                        ControlPanelSubsystem subsystemControlPanel, 
                        FuelShooterPIDSubsystem subsystemFuelPid, 
                        FuelDeliverySubSystem subsystemFuelDelivery){

        m_liftSubsystem = subsystemLift;
        m_driveSubsystem = subsystemDrive;
        m_controlPanelSubsystem = subsystemControlPanel;
        m_fuelShooterPIDSubsystem = subsystemFuelPid;
        m_fuelDeliverySubSystem = subsystemFuelDelivery;

        addRequirements(m_liftSubsystem);
        addRequirements(m_driveSubsystem);
        addRequirements(m_controlPanelSubsystem);
        addRequirements(m_fuelShooterPIDSubsystem);
        addRequirements(m_fuelDeliverySubSystem);

        addCommands(
            // Add Commands here:
            // Also add parallel commands using the
            //
            // addCommands(
            //      new command1(argsN, subsystem),
            //      parallel(
            //          new command2(argsN, subsystem),
            //          new command3(argsN, subsystem)
            //      )    
            //  );
            new FuelReleaseExtend(m_fuelDeliverySubSystem),
            new DriveReset(m_driveSubsystem),
            new WaitCommand(1),
            //new RamseteCommand_Demo(),
            new FuelReleaseRetract(m_fuelDeliverySubSystem)
        );

    }

    @Override
    public boolean runsWhenDisabled() {
        return false;

    }
}
