// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DriveSubsystem;

/**
 *
 */
public class DriveWait extends CommandBase {

    private final DriveSubsystem m_driveSubsystem;

    public DriveWait(DriveSubsystem subsystem) {

        m_driveSubsystem = subsystem;
        addRequirements(m_driveSubsystem);
       
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        System.out.print(" Waiting ");
        System.out.print(m_driveSubsystem.getLeftEncoderSpeed());
        System.out.print(" ");
        System.out.println(m_driveSubsystem.getRightEncoderSpeed());

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {

    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        if (m_driveSubsystem.getLeftEncoderSpeed() <= 0.1  && 
            m_driveSubsystem.getRightEncoderSpeed() <= 0.1  ) {
            return true;
        }
        else {
            return false;
        }
        
    }

    @Override
    public boolean runsWhenDisabled() {
        return false;

    }
}
